export const PagesConst = {
    OWNERREGISTER: 'REGISTRO DUEÑO DE SALAS',
    USERREGISTER: 'REGISTRO USUARIO',
    HOME: 'HOME',
    LOGIN: 'LOGIN',
    ROOMS: 'ROOMS',
    SONAMOS: 'SONAMOS',
    ROOMDETAIL: 'ROOMDETAIL',
    PROFILE: 'PROFILE',
    ADDROOM: 'ADDROOM',
}

export const UserObjectConst = {
    ID: 'ID', 
    NAME: 'NAME', 
    CONTACTNUMBER: 'CONTACTNUMBER',
    MAIL: 'MAIL',
    PASSWORD: 'PASSWORD',
    ISADMIN: 'ISADMIN',
    ROOMS: 'ROOMS',
}

export const RoomObjectConst = {
    NAME: 'NAME', 
    ADRESS: 'ADRESS', 
    DESCRIPTION: 'DESCRIPTION',
    GALLERY: 'GALLERY',
    AVAILABILITY: 'AVAILABILITY',
    PRICE: 'PRICE',
    ROOMS: 'ROOMS',
}

export const UserTypeConst = {
    OWNER: 'OWNER',
    USER: 'USER'
}

export const ReduxUserOwnerAction = {
    ADD_USEROWNER: 'ADD_USEROWNER',
    ADD_USEROWNER_FAILURE: 'ADD_USEROWNER_FAILURE',
    GET_USEROWNERS: 'GET_USEROWNERS',
    GET_USEROWNERS_FAILURE: 'GET_USEROWNERS_FAILURE',
    REMOVE_USEROWNER: 'REMOVE_USEROWNER',
    REMOVE_USEROWNER_FAILURE: 'REMOVE_USEROWNER_FAILURE',
    EDIT_USEROWNER: 'EDIT_USEROWNER',
    EDIT_USEROWNER_FAILURE: 'EDIT_USEROWNER_FAILURE',
    GET_USER_LOGGED: 'GET_USER_LOGGED',
    GET_USER_LOGGED_FAILURE: 'GET_USER_LOGGED_FAILURE',
    SET_USER_LOGGED: 'SET_USER_LOGGED',
    SET_USER_LOGGED_FAILURE: 'SET_USER_LOGGED_FAILURE',
    MODIFY_USER: 'MODIFY_USER',
    MODIFY_USER_FAILURE: 'MODIFY_USER_FAILURE',
    ADD_ALL_ROOMS: 'ADD_ALL_ROOMS',
    GET_ROOMS: 'GET_ROOMS',
    GET_ROOMS_FAILURE: 'GET_ROOMS_FAILURE'
}

export const TypeCard = {
    CARDMYROOM: 'CARDMYROOM',
    CARDALLROOMS: 'CARDALLROOMS'
}