export const PagesConst = {
    OWNERREGISTER: 'REGISTRO DUEÑO DE SALAS',
    USERREGISTER: 'REGISTRO USUARIO',
    HOME: 'HOME',
    LOGIN: 'LOGIN'
}

export const UserObjectConst = {
    ID: 'ID', 
    NAME: 'NAME', 
    CONTACTNUMBER: 'CONTACTNUMBER',
    MAIL: 'MAIL',
    PASSWORD: 'PASSWORD',
    ISADMIN: 'ISADMIN',
    ROOMS: 'ROOMS',
}

export const UserTypeConst = {
    OWNER: 'OWNER',
    USER: 'USER'
}

export const ReduxUserOwnerAction = {
    ADD_USEROWNER: 'ADD_USEROWNER',
    ADD_USEROWNER_FAILURE: 'ADD_USEROWNER_FAILURE',
    GET_USEROWNERS: 'GET_USEROWNERS',
    GET_USEROWNERS_FAILURE: 'GET_USEROWNERS_FAILURE',
    REMOVE_USEROWNER: 'REMOVE_USEROWNER',
    REMOVE_USEROWNER_FAILURE: 'REMOVE_USEROWNER_FAILURE',
    EDIT_USEROWNER: 'EDIT_USEROWNER',
    EDIT_USEROWNER_FAILURE: 'EDIT_USEROWNER_FAILURE'
}